<?php
/**
 * Copyright (c) 2019 - present
 * Laravel Auth Log - AuthLogTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 24/9/2019
 * MIT license: https://github.com/biscolab/laravel-authlog/blob/master/LICENSE
 */

namespace Biscolab\LaravelAuthLog\Tests;

use Biscolab\LaravelAuthLog\Models\AuthLog;
use Carbon\Carbon;

class AuthLogTest extends TestCase
{

    protected $user;

    protected $authlog;

    /**
     * @test
     */
    public function testUserHasLogins()
    {

        $this->user->load([
            'logins',
            'logouts',
            'forced_logouts',
        ]);

        $this->assertTrue($this->user->logins->count() > 0);
        $this->assertTrue($this->user->logouts->count() == 0);
        $this->assertTrue($this->user->forced_logouts->count() == 0);

    }

    /**
     * @test
     */
    public function testUserHasLogout()
    {

        $this->authlog->logged_out_at = Carbon::now();
        $this->authlog->save();

        $this->user->load([
            'logins',
            'logouts',
            'forced_logouts',
        ]);

        $this->assertTrue($this->user->logins->count() == 0);
        $this->assertTrue($this->user->logouts->count() > 0);
        $this->assertTrue($this->user->forced_logouts->count() == 0);
    }

    /**
     * @test
     */
    public function testUserHasForcedLogout()
    {

        $this->authlog->logged_out_at = Carbon::now();
        $this->authlog->blame_on_user_id = true;
        $this->authlog->save();

        $this->user->load([
            'logins',
            'logouts',
            'forced_logouts',
        ]);

        $this->assertTrue($this->user->logins->count() == 0);
        $this->assertTrue($this->user->logouts->count() == 0);
        $this->assertTrue($this->user->forced_logouts->count() > 0);

    }

    /**
     * @test
     */
    public function testUserHasForcedLogoutFromConsole()
    {

        $this->authlog->logged_out_at = Carbon::now();
        $this->authlog->killed_from_console = true;
        $this->authlog->save();

        $this->user->load([
            'logins',
            'logouts',
            'forced_logouts',
        ]);

        $this->assertTrue($this->user->logins->count() == 0);
        $this->assertTrue($this->user->logouts->count() == 0);
        $this->assertTrue($this->user->forced_logouts->count() > 0);

    }

    protected function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::create([
            'name'     => 'Roberto Belotti',
            'email'    => env('DEFAULT_USER_EMAIL'),
            'password' => bcrypt(env('DEFAULT_USER_PASSWORD'))
        ]);

        $this->authlog = AuthLog::create([
            'user_id'    => $this->user->id,
            'session_id' => \Biscolab\LaravelAuthLog\Facades\AuthLog::getCurrentSessionId()
        ]);

    }
}