<?php
/**
 * Copyright (c) 2019 - present
 * Laravel Auth Log - TestCase.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 18/9/2019
 * MIT license: https://github.com/biscolab/laravel-authlog/blob/master/LICENSE
 */

namespace Biscolab\LaravelAuthLog\Tests;

use Biscolab\LaravelAuthLog\AuthLogServiceProvider;
use Illuminate\Database\Schema\Blueprint;
use Orchestra\Testbench\TestCase as OrchestraTestCase;

/**
 * Class TestCase
 * @package Biscolab\LaravelAuthLog\Tests
 */
class TestCase extends OrchestraTestCase
{

    /**
     * Load package service provider
     *
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {

        return [AuthLogServiceProvider::class];
    }

    protected function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setUpDatabase($this->app);
    }

    /**
     * Set up the environment.
     *
     * @param \Illuminate\Foundation\Application $app
     */
    protected function getEnvironmentSetUp($app)
    {

        $app['config']->set('database.default', 'sqlite');
        $app['config']->set('database.connections.sqlite', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);

        $app['config']->set('cache.prefix', 'authlog_test_');
        $app['config']->set('authlog.enabled', true);
        $app['config']->set('auth.providers.users.model', User::class);
    }

    /**
     * Set up the database.
     *
     * @param \Illuminate\Foundation\Application $app
     */
    protected function setUpDatabase($app)
    {

        $schema_builder = $app['db']->connection()->getSchemaBuilder();

        // Users table
        $schema_builder->create('users', function (Blueprint $table) {

            $table->increments('id');
            $table->string('name', 255)->nullable();
            $table->string('email', 255);
            $table->nullableTimestamps();
        });

        // Sessions table
        $schema_builder->create('sessions', function (Blueprint $table) {

            $table->string('id', 255);
            $table->unsignedInteger('user_id')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->text('payload');
            $table->integer('last_activity');

            $table->unique('id', 'sessions_id_unique');

        });

        include_once __DIR__ . '/../database/migrations/2019_09_19_000000_create_authlog_table.php';

        (new \CreateAuthlogTable())->up();

    }
}
